[package]
name = "datacare"
version = "0.1.0"
edition = "2021"

[dependencies]
dump-dvb = { version = "0.6", git = "https://github.com/dump-dvb/dump-dvb.rs", features = ["management"]}
clap = { version = "4.0", features = ["derive"] }

actix-web = "4.0"
actix-identity = "*"
actix-session= { version = "0.7", features = ["redis-actor-session"] }

# serde serialization / deserialization
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }

# database
diesel = { version = "2", features = ["postgres", "r2d2", "uuid", "chrono"] }
r2d2 = "*"

# utils
uuid = { version = "*", features = ["serde", "v4"] }
env_logger = "*"
log = "*"
rand = "*"

utoipa = { version = "2", features = ["actix_extras"] }
regex = "*"
derive_more = "*"
